### ISSUE TITLE
Slack alerts error

### ISSUE THREAD

**Issue by nicolegys** [base-org/pessimism#160]
Hi, I get an error when the heuristic alerts to slack, which makes `pessimism_alerts_generated_total` metric doesn't work.
![1695732009777](https://github.com/base-org/pessimism/assets/43694095/9acca2b7-ab5c-4a07-acec-2e406e823069)

Found that, the response from slack is just a plain text "ok" or some error message like "channel not found", not a struct as below.
https://github.com/base-org/pessimism/blob/14481ced518b71995bac5b617f971ea9aaee367c/internal/client/slack.go#L77-L80

Could you please fix this issue? Pessimism works well for me.😀

**Comment by epociask** [comment]
Thanks for filing an issue! Hmmm, looks we may be using different Slack APIs then. I can add support for different host types to ensure cross compatibility between workspace API types. I wouldn't be able to get to this until the week after next (vacation) so there'd be a bit of a wait. You're more than welcome to do the implementation yourself if you need this compatibility sooner.  

Also I'm happy to hear that Pessimism is working well for you. Please lmk if there any other features/changes that you'd like seen 🙏🏻
