### ISSUE TITLE
Use Go Mock

### ISSUE THREAD

**Issue by epociask** [base-org/pessimism#26]
## Problem
Mocks used for testing are currently written manually using [testify/mock](github.com/stretchr/testify/mock). While this provides necessary functionality for testing, it doesn't scale well for the addition of new testing mocks and regeneration of existing ones.

## Problem Solution
[GoMock](https://github.com/golang/mock) provides mock autogeneration capabilities using embed instructions within Go files. 

### Acceptance Criteria
I. All current mocks (i.e, `EthClientInterface`) are regenerated using `mockgen` and stored as independent files in an `internal/mocks` package

II. All current mocks have embedded `gomock` instructions at the top of the code files which declare the interface that we'd like to mock. For example, to mock `EthClientInterface`, we add the following line to the top of `internal/client/eth_client.go`:
```
//go:generate mockgen -package=mocks -destination=../mocks/eth_client.go github.com/base-org/pessimism/internal/client EthClientInterface

```

III. Mock generation should be possible using a make command. _(e.g, `make mock-gen`)_

**Comment by vavrajosef** [comment]
Hello, I would like to work on this task. Please assign it to me.
