### ISSUE TITLE
`Pipeline` Lacks Introspective Capabilities into its Components

### ISSUE THREAD

**Issue by epociask** [base-org/pessimism#29]
## Problem
Existing `Pipeline` struct receiver logic has no support for an event loop routine that can read existing component states to understand when:
I. A component crashes or stops
II. An oracle component finishes backfilling: `syncing --> live`
III. (STRETCH) Inter-component communication latency is below some threshold

This logic is critical for the `etlManager` abstraction to be able to:
I. Perform merging operations when a `syncing` pipeline has become `live`; with there existing >1 identical pipelines with the same ID and `live` state
II. Understand when pipelines have successfully shutdown
IV. Understand when pipelines have crashed in real-time

## Proposed Solution
Two current possible solution paths, both of which are open for discussion:

### Solution 1: Higher Order Event Polling
This event loop should run in the following fashion to understand when key changes to component (consequently pipeline) state occur using some interval based polling algorithm like this:
```

while True:
  time.sleep(x)
  oracle_state = pipeline[0].state
  
  if pipeline.state != PipelineState(oracle_state): 
     pipeline.state = oracle_state
     emit pipeline.state
     
  for i, state in enumerate([c.state for c in pipeline]):
     if i == 0:
        continue
         
     if state != "active" :
        pipeline.state = state
        emit pipeline.state 
```

This issues with this approach are:
I. Polling increases computational load 
II. Increased latency given time discrepancies between when a component state change happens versus when the poller performs a pipeline read

## Solution 2: Event Based
Otherwise, a more event (listener/subscriber) based model could be leveraged where the pipeline is actively listening for components to emit activationState events. This 

The issues with this approach are:
I. _(abstraction leak)_ Components need to have higher order knowledge (i.e, go channel) of the greater Pipeline. 
II. Increased concurrency management.

### NOTE
These proposed solutions don't take failure management into considerations For example, in the instance of a failed pipeline, we could enact some retry procedure to re-attempt running it `N` times. These fail safe or recovery procedures should be explored in a subsequent issue.

**Comment by epociask** [comment]
@anupsv-cb @nadir-akhtar-coinbase Would love y'alls feedback &/or ideas on the solution routes here :)

**Comment by nadir-akhtar-coinbase** [comment]
Potentially another issue, what about sighandling for panic situations? This would be difficult to detect in the rare event it would happen, but I am curious if this is an elegant way to guarantee the behavior upon a crash

**Comment by epociask** [comment]
After looking into this and discussing with @nadir-akhtar-coinbase further, it may be better suited for the `etlManager` to have a separate eventLoop where it performs management operations over every etl pipeline like:
1. Updating `activityState` for pipelines based on component state events
2. Merging pipelines when activityState for the same pipeline IDs collide
