### ISSUE TITLE
State Key Representation is Insecure

### ISSUE THREAD

**Issue by epociask** [base-org/pessimism#69]
## Problem 
The current state key representation is very insecure given that a struct is used with no pointer references by the respective stateful component definitions. Currently this results in data loss of the state keys that are held in the component's structure once higher level callers garbage collect the value. Because of this, active components fail to lookup necessary stateful values for secure operation 

This bug is currently only prevalent in the current `account_balance` oracle [implementation](https://github.com/base-org/pessimism/blob/master/internal/etl/registry/oracle/account_balance.go), consequently resulting in the existing `balance_enforcement` invariant to not work. 

There are some bandaid fixes that we could easily apply to remediate this in the short-term:
I. Make the `balance_oracle` store a reference to the stateKey type instead of a direct value

However, the fundamental representation of the key itself is flawed as by nature it should be a low-memory primitive type. Additionally, a lower level representation would ensure that there'd be need to no have a string representation in memory. 

## Problem Solution - 1  (32 byte array)
Update state key representation to be adherent with existing ID representations that are already used across the application. A byte slice representation would be ideal that encodes the necessary metadata for stateful lookups using the following 256 bit representation:
```
type StateKey [32]byte
```

With a byte encoding schema like:
```
0       1        2        3                      22           32
|-------|--------|--------|----------------------|--------------|

nested    prefix  register     (optional) address         PUUID
                     byte
 ```
 
 This would avoid the need for pointers when referencing keys.
 Additionally, chars in go occupy `4 bytes`, meaning that this rep stored as a string would be `128` bytes versus `32`. 
 
 ## Problem Solution - 2 (57 byte struct)
 Store references to state keys in the oracle metadata. This would require keeping the existing state key struct types as is; ie:
```
// StateKey ... Represents a key in the state store
type StateKey struct {
	Nested bool // Indicates whether the key is nested
	Prefix uint8
	Key    string
}

func (sk StateKey) IsNested() bool {
	return sk.Nested
}

// WithPUUID ... Adds a pipeline UUID to the state key prefix and returns a new state key
func (sk StateKey) WithPUUID(pUUID PipelineUUID) StateKey {
	return StateKey{
		sk.Nested,
		sk.Prefix,
		pUUID.String() + ":" + sk.Key,
	}
}
```
 **NOTE: We should probably update the struct definition to store the PUUID instead of doing a string concatenation inside a  clone method**

### Versus solution - 1 
In comparison to solution - 1, 2 will occupy more space as the `Nested` value would be a boolean; occupying 4 bytes instead of 1 and would require holding 25 bytes for the entire `PUUID`. However, other data fields `(ie. nested, prefix, registerType, address)` would occupy the same space as they do in solution - 1. It's important to note that this solution is more intuitive for developers and readability purposes.

**Comment by nadir-akhtar-coinbase** [comment]
It would be helpful to point to particular locations in code where state keys aren’t particularly well managed, hard to wholly understand how the problem manifests

**Comment by epociask** [comment]
@nadir-akhtar-coinbase Updated the issue, please lmk what you think and what solution you're leaning towards :)

**Comment by nadir-akhtar-coinbase** [comment]
This is totally helpful. Curious why it's the `account_balance` oracle specifically that seems to be failing.

As for the solutions, I prefer 2 for readability even given the memory costs, but depends on the scale at which these memory costs will be impactful too. I don't anticipate it being prohibitively expensive

**Comment by epociask** [comment]
Closed by https://github.com/base-org/pessimism/pull/83
