### ISSUE TITLE
Markdown Linting Support

### ISSUE THREAD

**Issue by epociask** [base-org/pessimism#96]
## Problem 
Many of the existing repo markdown documents are riddled with typos and formatting issues. This can cause confusion for users and is nonetheless poor hygiene. Adding markdown linting will help establish a consistent formatting style for Markdown files.

## Problem Solution
* Integrated markdown linting in CI
* Make directive to run markdown linter
* Repo passing markdown linting scan

**Comment by alessandromazza98** [comment]
Hi, I can take this.

I was thinking about markdownlint, should it be ok?

**Comment by epociask** [comment]
Hey @alessandromazza98, that'll be fine 🙏🏻
